In [3]:
# Kaggle Dataset

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("ai_model_arena_rankings.csv.csv")
df

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
0,vicuna-13b,LMSYS,Llama 2 Community,1094.000000,NaN,NaN,NaN,NaN,1.0,overall,2023-05-08,text
1,koala-13b,UC Berkeley,Non-commercial,1015.000000,NaN,NaN,NaN,NaN,2.0,overall,2023-05-08,text
2,RWKV-4-Raven-14B,RWKV,Apache 2.0,979.000000,NaN,NaN,NaN,NaN,3.0,overall,2023-05-08,text
3,oasst-pythia-12b,OpenAssistant,Apache 2.0,941.000000,NaN,NaN,NaN,NaN,4.0,overall,2023-05-08,text
4,alpaca-13b,Stanford,Non-commercial,935.000000,NaN,NaN,NaN,NaN,5.0,overall,2023-05-08,text
...,...,...,...,...,...,...,...,...,...,...,...,...
97372,gpt-5-search,openai,Proprietary,1132.337817,1126.606514,1138.069120,8.550874,20926.0,28.0,overall,2026-07-02,search
97373,ppl-sonar-pro-high,Perplexity,Proprietary,1129.385404,1123.784031,1134.986777,8.167568,28717.0,29.0,overall,2026-07-02,search
97374,claude-opus-4-search,anthropic,Proprietary,1126.476734,1121.269185,1131.684283,7.059444,31225.0,30.0,overall,2026-07-02,search
97375,diffbot-small-xl,diffbot,Apache 2.0,1022.913853,1014.656947,1031.170759,17.747554,6436.0,31.0,overall,2026-07-02,search
97376,api-gpt-4o-search,openai,Proprietary,1006.215621,995.270359,1017.160882,31.185742,3441.0,32.0,overall,2026-07-02,search

In [6]:
df.head()

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
0,vicuna-13b,LMSYS,Llama 2 Community,1094.0,NaN,NaN,NaN,NaN,1.0,overall,2023-05-08,text
1,koala-13b,UC Berkeley,Non-commercial,1015.0,NaN,NaN,NaN,NaN,2.0,overall,2023-05-08,text
2,RWKV-4-Raven-14B,RWKV,Apache 2.0,979.0,NaN,NaN,NaN,NaN,3.0,overall,2023-05-08,text
3,oasst-pythia-12b,OpenAssistant,Apache 2.0,941.0,NaN,NaN,NaN,NaN,4.0,overall,2023-05-08,text
4,alpaca-13b,Stanford,Non-commercial,935.0,NaN,NaN,NaN,NaN,5.0,overall,2023-05-08,text

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97377 entries, 0 to 97376
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   model_name                97377 non-null  object
 1   organization              93900 non-null  object
 2   license                   97246 non-null  object
 3   rating                    97377 non-null  float64
 4   rating_lower              97070 non-null  float64
 5   rating_upper              97070 non-null  float64
 6   variance                  97070 non-null  float64
 7   vote_count                97070 non-null  float64
 8   rank                      97377 non-null  float64
 9   category                  97377 non-null  object
 10  leaderboard_publish_date  97377 non-null  object
 11  subset                    97377 non-null  object
dtypes: float64(6), object(6)
memory usage: 8.9+ MB

In [8]:
df.describe()

,rating,rating_lower,rating_upper,variance,vote_count,rank
count,97377.000000,97070.000000,97070.000000,97070.000000,97070.000000,97377.000000
mean,1232.582439,1226.333891,1240.476336,16.858066,23586.333728,119.164197
std,145.454932,146.240327,143.613960,20.661015,27389.381794,89.941677
min,789.000000,782.043296,800.000000,0.000000,54.000000,1.000000
25%,1125.959993,1119.161926,1135.238584,4.967224,5243.000000,43.000000
50%,1240.190789,1234.672228,1247.290220,10.444272,12857.000000,99.000000
75%,1348.771914,1343.719372,1356.460212,22.175828,32191.000000,180.000000
max,1664.985725,1644.632424,1685.339027,777.424034,202735.000000,374.000000


                              SELECTING DATA

In [9]:
df["license"]

0        Llama 2 Community
1           Non-commercial
2               Apache 2.0
3               Apache 2.0
4           Non-commercial
               ...
97372          Proprietary
97373          Proprietary
97374          Proprietary
97375           Apache 2.0
97376          Proprietary
Name: license, Length: 97377, dtype: object

In [10]:
df["model_name"]

0                  vicuna-13b
1                   koala-13b
2            RWKV-4-Raven-14B
3            oasst-pythia-12b
4                  alpaca-13b
                 ...
97372            gpt-5-search
97373      ppl-sonar-pro-high
97374    claude-opus-4-search
97375        diffbot-small-xl
97376       api-gpt-4o-search
Name: model_name, Length: 97377, dtype: object

In [11]:
df[["model_name", "license"]]

                 model_name            license
0                vicuna-13b  Llama 2 Community
1                 koala-13b     Non-commercial
2          RWKV-4-Raven-14B         Apache 2.0
3          oasst-pythia-12b         Apache 2.0
4                alpaca-13b     Non-commercial
...                     ...                ...
97372          gpt-5-search        Proprietary
97373    ppl-sonar-pro-high        Proprietary
97374  claude-opus-4-search        Proprietary
97375      diffbot-small-xl         Apache 2.0
97376     api-gpt-4o-search        Proprietary

[97377 rows x 2 columns]

In [16]:
# Select rows ( label & index based )
# loc and iloc
print(df.loc[0])
print(df.loc[0:3])  # in loc ending index is inclusive
print("")
print("")
print("")
print(df.iloc[0])
print(df.iloc[0:3])  # in iloc ending index is exclusive

model_name                         vicuna-13b
organization                            LMSYS
license                     Llama 2 Community
rating                                 1094.0
rating_lower                              NaN
rating_upper                              NaN
variance                                  NaN
vote_count                                NaN
rank                                      1.0
category                              overall
leaderboard_publish_date           2023-05-08
subset                                   text
Name: 0, dtype: object
         model_name   organization            license  rating  rating_lower  \
0        vicuna-13b          LMSYS  Llama 2 Community  1094.0           NaN
1         koala-13b    UC Berkeley     Non-commercial  1015.0           NaN
2  RWKV-4-Raven-14B           RWKV         Apache 2.0   979.0           NaN
3  oasst-pythia-12b  OpenAssistant         Apache 2.0   941.0           NaN

   rating_upper  variance  vote_count  rank category leaderboard_publish_date  \
0           NaN       NaN         NaN   1.0  overall               2023-05-08
1           NaN       NaN         NaN   2.0  overall               2023-05-08
2           NaN       NaN         NaN   3.0  overall               2023-05-08
3           NaN       NaN         NaN   4.0  overall               2023-05-08

  subset
0   text
1   text
2   text
3   text

model_name                         vicuna-13b
organization                            LMSYS
license                     Llama 2 Community
rating                                 1094.0
rating_lower                              NaN
rating_upper                              NaN
variance                                  NaN
vote_count                                NaN
rank                                      1.0
category                              overall
leaderboard_publish_date           2023-05-08
subset                                   text
Name: 0, dtype: object
         model_name organization            license  rating  rating_lower  \
0        vicuna-13b        LMSYS  Llama 2 Community  1094.0           NaN
1         koala-13b  UC Berkeley     Non-commercial  1015.0           NaN
2  RWKV-4-Raven-14B         RWKV         Apache 2.0   979.0           NaN

   rating_upper  variance  vote_count  rank category leaderboard_publish_date  \
0           NaN       NaN         NaN   1.0  overall               2023-05-08
1           NaN       NaN         NaN   2.0  overall               2023-05-08
2           NaN       NaN         NaN   3.0  overall               2023-05-08

  subset
0   text
1   text
2   text

In [28]:
# cells - rows , column
df.loc[0,"license"]
df.loc[0:2, ["license" , "rating" , "organization"]]

df.iloc[0:2, 0:3]
df.iloc[1, 2]
        
df.iloc[0:3, 0:4]

         model_name organization            license  rating
0        vicuna-13b        LMSYS  Llama 2 Community  1094.0
1         koala-13b  UC Berkeley     Non-commercial  1015.0
2  RWKV-4-Raven-14B         RWKV         Apache 2.0   979.0

In [19]:
df

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
0,vicuna-13b,LMSYS,Llama 2 Community,1094.000000,NaN,NaN,NaN,NaN,1.0,overall,2023-05-08,text
1,koala-13b,UC Berkeley,Non-commercial,1015.000000,NaN,NaN,NaN,NaN,2.0,overall,2023-05-08,text
2,RWKV-4-Raven-14B,RWKV,Apache 2.0,979.000000,NaN,NaN,NaN,NaN,3.0,overall,2023-05-08,text
3,oasst-pythia-12b,OpenAssistant,Apache 2.0,941.000000,NaN,NaN,NaN,NaN,4.0,overall,2023-05-08,text
4,alpaca-13b,Stanford,Non-commercial,935.000000,NaN,NaN,NaN,NaN,5.0,overall,2023-05-08,text
...,...,...,...,...,...,...,...,...,...,...,...,...
97372,gpt-5-search,openai,Proprietary,1132.337817,1126.606514,1138.069120,8.550874,20926.0,28.0,overall,2026-07-02,search
97373,ppl-sonar-pro-high,Perplexity,Proprietary,1129.385404,1123.784031,1134.986777,8.167568,28717.0,29.0,overall,2026-07-02,search
97374,claude-opus-4-search,anthropic,Proprietary,1126.476734,1121.269185,1131.684283,7.059444,31225.0,30.0,overall,2026-07-02,search
97375,diffbot-small-xl,diffbot,Apache 2.0,1022.913853,1014.656947,1031.170759,17.747554,6436.0,31.0,overall,2026-07-02,search
97376,api-gpt-4o-search,openai,Proprietary,1006.215621,995.270359,1017.160882,31.185742,3441.0,32.0,overall,2026-07-02,search

In [30]:
df.at[97376, "organization"]

'openai'

In [31]:
df.iat[97376, 1]

# at and iat mainly used for selecting the scalar value

'openai'

In [32]:
df.loc[97376,"organization"]

'openai'


here view is created not copy 
and if you want to change the original data then it is good practice to use copy() method.