In [1]:
# FILTEIRING DATA

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("ai_model_arena_rankings.csv.csv")

In [9]:
df[df["rating"] > 1500]

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
26496,claude-opus-4-6-thinking,anthropic,Proprietary,1501.424996,1486.655285,1516.194706,56.786854,1579.0,1.0,overall,2026-02-06,text
26802,claude-opus-4-6-thinking,anthropic,Proprietary,1502.566061,1492.161448,1512.970674,28.180953,3401.0,1.0,overall,2026-02-09,text
27109,claude-opus-4-6-thinking,anthropic,Proprietary,1503.043515,1493.058178,1513.028853,25.955496,3679.0,1.0,overall,2026-02-10,text
27110,claude-opus-4-6,anthropic,Proprietary,1500.587897,1491.432974,1509.742820,21.817915,4427.0,2.0,overall,2026-02-10,text
27417,claude-opus-4-6-thinking,anthropic,Proprietary,1503.647554,1493.926461,1513.368646,24.599933,3922.0,1.0,overall,2026-02-11,text
...,...,...,...,...,...,...,...,...,...,...,...,...
96702,glm-5.1,zai,MIT,1526.672623,1517.530417,1535.814830,21.757345,5349.0,14.0,overall,2026-07-10,webdev
96703,claude-sonnet-4-6,anthropic,Proprietary,1521.101619,1515.248216,1526.955023,8.919094,15725.0,15.0,overall,2026-07-10,webdev
96704,qwen3.7-max-20260517,alibaba,Proprietary,1520.682224,1512.005520,1529.358929,19.598076,5874.0,16.0,overall,2026-07-10,webdev
96705,kimi-k2.6,moonshot,Modified MIT,1513.264425,1505.835343,1520.693507,14.367266,8868.0,17.0,overall,2026-07-10,webdev
96706,gpt-5.5-xhigh (codex-harness),openai,Proprietary,1501.976164,1494.628783,1509.323544,14.052993,8601.0,18.0,overall,2026-07-10,webdev

In [15]:
df[(df["rating"] > 1500) & (df["rank"] < 100) ]

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
26496,claude-opus-4-6-thinking,anthropic,Proprietary,1501.424996,1486.655285,1516.194706,56.786854,1579.0,1.0,overall,2026-02-06,text
26802,claude-opus-4-6-thinking,anthropic,Proprietary,1502.566061,1492.161448,1512.970674,28.180953,3401.0,1.0,overall,2026-02-09,text
27109,claude-opus-4-6-thinking,anthropic,Proprietary,1503.043515,1493.058178,1513.028853,25.955496,3679.0,1.0,overall,2026-02-10,text
27110,claude-opus-4-6,anthropic,Proprietary,1500.587897,1491.432974,1509.742820,21.817915,4427.0,2.0,overall,2026-02-10,text
27417,claude-opus-4-6-thinking,anthropic,Proprietary,1503.647554,1493.926461,1513.368646,24.599933,3922.0,1.0,overall,2026-02-11,text
...,...,...,...,...,...,...,...,...,...,...,...,...
96702,glm-5.1,zai,MIT,1526.672623,1517.530417,1535.814830,21.757345,5349.0,14.0,overall,2026-07-10,webdev
96703,claude-sonnet-4-6,anthropic,Proprietary,1521.101619,1515.248216,1526.955023,8.919094,15725.0,15.0,overall,2026-07-10,webdev
96704,qwen3.7-max-20260517,alibaba,Proprietary,1520.682224,1512.005520,1529.358929,19.598076,5874.0,16.0,overall,2026-07-10,webdev
96705,kimi-k2.6,moonshot,Modified MIT,1513.264425,1505.835343,1520.693507,14.367266,8868.0,17.0,overall,2026-07-10,webdev
96706,gpt-5.5-xhigh (codex-harness),openai,Proprietary,1501.976164,1494.628783,1509.323544,14.052993,8601.0,18.0,overall,2026-07-10,webdev

In [5]:
df

,model_name,organization,license,rating,rating_lower,rating_upper,variance,vote_count,rank,category,leaderboard_publish_date,subset
0,vicuna-13b,LMSYS,Llama 2 Community,1094.000000,NaN,NaN,NaN,NaN,1.0,overall,2023-05-08,text
1,koala-13b,UC Berkeley,Non-commercial,1015.000000,NaN,NaN,NaN,NaN,2.0,overall,2023-05-08,text
2,RWKV-4-Raven-14B,RWKV,Apache 2.0,979.000000,NaN,NaN,NaN,NaN,3.0,overall,2023-05-08,text
3,oasst-pythia-12b,OpenAssistant,Apache 2.0,941.000000,NaN,NaN,NaN,NaN,4.0,overall,2023-05-08,text
4,alpaca-13b,Stanford,Non-commercial,935.000000,NaN,NaN,NaN,NaN,5.0,overall,2023-05-08,text
...,...,...,...,...,...,...,...,...,...,...,...,...
97372,gpt-5-search,openai,Proprietary,1132.337817,1126.606514,1138.069120,8.550874,20926.0,28.0,overall,2026-07-02,search
97373,ppl-sonar-pro-high,Perplexity,Proprietary,1129.385404,1123.784031,1134.986777,8.167568,28717.0,29.0,overall,2026-07-02,search
97374,claude-opus-4-search,anthropic,Proprietary,1126.476734,1121.269185,1131.684283,7.059444,31225.0,30.0,overall,2026-07-02,search
97375,diffbot-small-xl,diffbot,Apache 2.0,1022.913853,1014.656947,1031.170759,17.747554,6436.0,31.0,overall,2026-07-02,search
97376,api-gpt-4o-search,openai,Proprietary,1006.215621,995.270359,1017.160882,31.185742,3441.0,32.0,overall,2026-07-02,search

In [17]:
df[df["rating"] > 1600][["model_name" , "organization"]]

                              model_name organization
96059                     claude-fable-5    anthropic
96145                     claude-fable-5    anthropic
96233                     claude-fable-5    anthropic
96323                     claude-fable-5    anthropic
96413                     claude-fable-5    anthropic
96503                     claude-fable-5    anthropic
96595                     claude-fable-5    anthropic
96689                     claude-fable-5    anthropic
96690  gpt-5.6-sol-xhigh (codex-harness)       openai

In [21]:
filter_data = df[df["rating"] > 1600][["model_name" , "organization"]]
print(filter_data.iloc[0])
# print(filter_data.loc[0]) it shows error because labels are preserve 
print("")
print(filter_data.loc[96059])

model_name      claude-fable-5
organization         anthropic
Name: 96059, dtype: object

model_name      claude-fable-5
organization         anthropic
Name: 96059, dtype: object


query method to filtering the data 
it returns copy not view

In [29]:
df.query("rating > 1600 & rank < 20")[["model_name" , "organization"]]

                              model_name organization
96059                     claude-fable-5    anthropic
96145                     claude-fable-5    anthropic
96233                     claude-fable-5    anthropic
96323                     claude-fable-5    anthropic
96413                     claude-fable-5    anthropic
96503                     claude-fable-5    anthropic
96595                     claude-fable-5    anthropic
96689                     claude-fable-5    anthropic
96690  gpt-5.6-sol-xhigh (codex-harness)       openai

In [31]:
ranking = 20
df.query("rating >= 1600 & rank < @ranking")[["model_name" , "organization"]]

                              model_name organization
96059                     claude-fable-5    anthropic
96145                     claude-fable-5    anthropic
96233                     claude-fable-5    anthropic
96323                     claude-fable-5    anthropic
96413                     claude-fable-5    anthropic
96503                     claude-fable-5    anthropic
96595                     claude-fable-5    anthropic
96689                     claude-fable-5    anthropic
96690  gpt-5.6-sol-xhigh (codex-harness)       openai

In [33]:
fil_data = df.query("rating >= 1600 & rank < @ranking")[["model_name" , "organization"]].copy()
fil_data
# it is good practice to use .copy() method

                              model_name organization
96059                     claude-fable-5    anthropic
96145                     claude-fable-5    anthropic
96233                     claude-fable-5    anthropic
96323                     claude-fable-5    anthropic
96413                     claude-fable-5    anthropic
96503                     claude-fable-5    anthropic
96595                     claude-fable-5    anthropic
96689                     claude-fable-5    anthropic
96690  gpt-5.6-sol-xhigh (codex-harness)       openai

In [34]:
df.isnull().sum()

model_name                     0
organization                3477
license                      131
rating                         0
rating_lower                 307
rating_upper                 307
variance                     307
vote_count                   307
rank                           0
category                       0
leaderboard_publish_date       0
subset                         0
dtype: int64