In [1]:
# Transforming Data (Feature Engg)
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
df2 = df.copy()

In [8]:
df2["tax"] = df2["income"].apply(lambda x : "20%" if x>=50000 else "10%" )
df2

    id          name   age country   gender   income  tex  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%  20%
6    6           NaN  45.0   India   Female  73000.0  20%  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%  20%

In [14]:
# Male -> M
# Female -> F
# Unknown -> U
gender_map = {"Male" : "M", "Female": "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tex  tax
0    1      John Doe  29.0     USA      M  55000.0  20%  20%
1    1      John Doe  29.0     USA      M  55000.0  20%  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%  20%
3    3          Alex   NaN     USA      U  47000.0  10%  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%  10%
5    5        Li Wei  27.0   China      M  51000.0  20%  20%
6    6           NaN  45.0   India      F  73000.0  20%  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%  20%

In [16]:
df2.assign(new_income = df2["income"] * 1.1)

    id          name   age country gender   income  tex  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%  20%     63800.0

In [18]:
df2["country"] = df2["country"].replace("USA" , "America")
df2

    id          name   age  country gender   income  tex  tax
0    1      John Doe  29.0  America      M  55000.0  20%  20%
1    1      John Doe  29.0  America      M  55000.0  20%  20%
2    2    Jane Smith   NaN   Canada      F  62000.0  20%  20%
3    3          Alex   NaN  America      U  47000.0  10%  10%
4    4  Maria Garcia  34.0    Spain      F      NaN  10%  10%
5    5        Li Wei  27.0    China      M  51000.0  20%  20%
6    6           NaN  45.0    India      F  73000.0  20%  20%
7    7    Ahmed Khan  38.0      NaN      M  68000.0  20%  20%
8    8    Rachel Lee  29.0  America      F  62000.0  20%  20%
9    9   Carlos Ruiz   NaN   Mexico      M  45000.0  10%  10%
10  10   Emily Davis  31.0  America    NaN  58000.0  20%  20%