In [1]:
# other imp. function to transforming the data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df2 = df.copy()

In [9]:
df2.columns = ["ID", "NAME" , "AGE" , "COUNTRY" , "GENDER" , "INCOME"]

In [10]:
df2

    ID          NAME   AGE COUNTRY   GENDER   INCOME
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
# INCOME ---> Salary
df2.rename(columns = {"INCOME" : "Salary"})

    ID          NAME   AGE COUNTRY   GENDER   Salary
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
# if want to rename the lable name
df2.rename(index = {0 : "Zero" , 1 : "first"})

       ID          NAME   AGE COUNTRY   GENDER   INCOME
Zero    1      John Doe  29.0     USA     Male  55000.0
first   1      John Doe  29.0     USA     Male  55000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0
3       3          Alex   NaN     USA  Unknown  47000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
5       5        Li Wei  27.0   China     Male  51000.0
6       6           NaN  45.0   India   Female  73000.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0

In [48]:
df2 = df2.fillna(50)
# sort_inc = df2.sort_values("INCOME" , ascending =False)
sorted_data = df2.sort_values(["INCOME" , "AGE"])
sorted_data

    ID          NAME   AGE COUNTRY   GENDER   INCOME
4    4  Maria Garcia  34.0   Spain   Female     50.0
9    9   Carlos Ruiz  50.0  Mexico     Male  45000.0
3    3          Alex  50.0     USA  Unknown  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
10  10   Emily Davis  31.0     USA       50  58000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
2    2    Jane Smith  50.0  Canada   Female  62000.0
7    7    Ahmed Khan  38.0      50     Male  68000.0
6    6            50  45.0   India   Female  73000.0

In [38]:
sorted_data.sort_index()

    ID          NAME   AGE COUNTRY   GENDER   INCOME
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  50.0  Canada   Female  62000.0
3    3          Alex  50.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female     50.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6            50  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0      50     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  50.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA       50  58000.0

In [39]:
# reset
sorted_data.reset_index()

# and we can also drop our old index by doing
sorted_data.reset_index(drop = True)

    index  ID          NAME   AGE COUNTRY   GENDER   INCOME
0       6   6            50  45.0   India   Female  73000.0
1       7   7    Ahmed Khan  38.0      50     Male  68000.0
2       2   2    Jane Smith  50.0  Canada   Female  62000.0
3       8   8    Rachel Lee  29.0     USA   Female  62000.0
4      10  10   Emily Davis  31.0     USA       50  58000.0
5       0   1      John Doe  29.0     USA     Male  55000.0
6       1   1      John Doe  29.0     USA     Male  55000.0
7       5   5        Li Wei  27.0   China     Male  51000.0
8       3   3          Alex  50.0     USA  Unknown  47000.0
9       9   9   Carlos Ruiz  50.0  Mexico     Male  45000.0
10      4   4  Maria Garcia  34.0   Spain   Female     50.0

In [53]:
# ranking our data
sorted_data["Ranking"] = sorted_data["INCOME"].rank(ascending = False)
sorted_data
# and you don't want that kind of values like 6.5 and 6.5 then you can change it by doing this
sorted_data["Ranking"] = sorted_data["INCOME"].rank(ascending = False , method = "dense")
sorted_data

    ID          NAME   AGE COUNTRY   GENDER   INCOME  Ranking
4    4  Maria Garcia  34.0   Spain   Female     50.0      9.0
9    9   Carlos Ruiz  50.0  Mexico     Male  45000.0      8.0
3    3          Alex  50.0     USA  Unknown  47000.0      7.0
5    5        Li Wei  27.0   China     Male  51000.0      6.0
0    1      John Doe  29.0     USA     Male  55000.0      5.0
1    1      John Doe  29.0     USA     Male  55000.0      5.0
10  10   Emily Davis  31.0     USA       50  58000.0      4.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      3.0
2    2    Jane Smith  50.0  Canada   Female  62000.0      3.0
7    7    Ahmed Khan  38.0      50     Male  68000.0      2.0
6    6            50  45.0   India   Female  73000.0      1.0

In [ ]:
# reorder our columns
sorted_data[["ID" , "AG"]]

In [19]:
df2

    ID          NAME   AGE COUNTRY   GENDER   INCOME
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0