In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sorted_data.csv")
df

   Unnamed: 0  id          name   age country   gender   income
0           0   4  Maria Garcia  34.0   Spain   Female      0.0
1           1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2           2   3          Alex   0.0     USA  Unknown  47000.0
3           3   5        Li Wei  27.0   China     Male  51000.0
4           4   1      John Doe  29.0     USA     Male  55000.0
5           5  10   Emily Davis  31.0     USA        0  58000.0
6           6   2    Jane Smith   0.0  Canada   Female  62000.0
7           7   8    Rachel Lee  29.0     USA   Female  62000.0
8           8   7    Ahmed Khan  38.0       0     Male  68000.0
9           9   6             0  45.0   India   Female  73000.0

In [4]:
df.groupby("gender")["age"].mean()

gender
0          31.0
Female     27.0
Male       23.5
Unknown     0.0
Name: age, dtype: float64

In [6]:
df.groupby("gender")["income"].max()

gender
0          58000.0
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [7]:
df.groupby("country")["age"].min()

country
0         38.0
Canada     0.0
China     27.0
India     45.0
Mexico     0.0
Spain     34.0
USA        0.0
Name: age, dtype: float64

In [8]:
df.groupby("country")["income"].agg(["min","mean","max"])

             min     mean      max
country
0        68000.0  68000.0  68000.0
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        0.0      0.0      0.0
USA      47000.0  55500.0  62000.0

In [9]:
# .aggregate() is same as .agg()
df.groupby("country")["income"].aggregate(["min","mean","max"])

             min     mean      max
country
0        68000.0  68000.0  68000.0
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        0.0      0.0      0.0
USA      47000.0  55500.0  62000.0

In [10]:
df.groupby("country")["income"].aggregate(min_income = "min",avg_income = "mean",max_income = "max")

         min_income  avg_income  max_income
country
0           68000.0     68000.0     68000.0
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           0.0         0.0         0.0
USA         47000.0     55500.0     62000.0

In [15]:
df.groupby("country").agg({
    "income" : "mean",
    "age" : "min"
})

          income   age
country
0        68000.0  38.0
Canada   62000.0   0.0
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   0.0
Spain        0.0  34.0
USA      55500.0   0.0

In [16]:
df.groupby("gender").agg({
    "income" : "mean",
    "age" : "mean"
})

          income   age
gender
0        58000.0  31.0
Female   49250.0  27.0
Male     54750.0  23.5
Unknown  47000.0   0.0

In [17]:
df.groupby("country").agg(
    max_salary=("income", "max"),
    avg_age=("age", "mean")
)

         max_salary  avg_age
country
0           68000.0    38.00
Canada      62000.0     0.00
China       51000.0    27.00
India       73000.0    45.00
Mexico      45000.0     0.00
Spain           0.0    34.00
USA         62000.0    22.25