In [1]:
# Melt and pivot

In [2]:
import pandas as pd

In [8]:
df = pd.DataFrame({
    "Country": ["USA" , "IND" , "AUS" , "ENG" , "CHINA"] ,
    "Avg_Age": [60,55,73,74,80],
    "Year"   : [2022,2022,2021,2025,2024] ,
    "Income" : [90000,15000,80000,97332,99000],
    "Tax"    : [12,18,12,10,8]
})

In [9]:
df

  Country  Avg_Age  Year  Income  Tax
0     USA       60  2022   90000   12
1     IND       55  2022   15000   18
2     AUS       73  2021   80000   12
3     ENG       74  2025   97332   10
4   CHINA       80  2024   99000    8

now this df is in wide formate if you want to convert it into long formate for better performance of your model 
then you use the concept of melt and in this we also preserve our values
melt means you convert wode formate to the long formate
syntax:
        melt(id_vars , value_vars , var_name , value_name)

In [17]:
melted_data = df.melt( id_vars = ["Country" , "Year"],
     value_vars = ["Income","Tax","Avg_Age"],
     var_name = "Total_Salary_with_Age",
     value_name = "value")
melted_data

   Country  Year Total_Salary_with_Age  value
0      USA  2022                Income  90000
1      IND  2022                Income  15000
2      AUS  2021                Income  80000
3      ENG  2025                Income  97332
4    CHINA  2024                Income  99000
5      USA  2022                   Tax     12
6      IND  2022                   Tax     18
7      AUS  2021                   Tax     12
8      ENG  2025                   Tax     10
9    CHINA  2024                   Tax      8
10     USA  2022               Avg_Age     60
11     IND  2022               Avg_Age     55
12     AUS  2021               Avg_Age     73
13     ENG  2025               Avg_Age     74
14   CHINA  2024               Avg_Age     80

In [18]:
original_data = melted_data.pivot(
    index = ["Country"] ,
    columns = "Total_Salary_with_Age",
    values =   "value"      
)

In [19]:

original_data

Total_Salary_with_Age  Avg_Age  Income  Tax
Country
AUS                         73   80000   12
CHINA                       80   99000    8
ENG                         74   97332   10
IND                         55   15000   18
USA                         60   90000   12